#!/bin/bash
#Add webserver
/show/description "Install pigetcam"
/system/downloadModule nginx
/do/nginx/install
/do/nginx/dir "/opt/piget/pigetcam/www"
/system/install php5-curl

/show/listecho "Copy configurations" $OK
/system/makedir /opt/user/config/pigetcam
if [ -e "/boot/piget/config/pigetcam" ];then
  cp -v /boot/piget/config/pigetcam/* /opt/user/config/pigetcam
else
  cp -v /opt/piget/pigetcam/default/* /opt/user/config/pigetcam
fi

/show/listecho "Authorize reboot/halt" $OK
/do/nginx/authorize "/sbin/reboot"
/do/nginx/authorize "/sbin/halt"

/show/listecho "Authorize pilight controls" $OK
/do/nginx/authorize "/do/pilightCommand/start"
/do/nginx/authorize "/do/pilightCommand/stop"

/show/listecho "Authorize email" $OK
/do/nginx/authorize "/do/pigetcam/sendPicture"

/show/listecho "Authorize Camera Stream" $OK
/do/nginx/authorize "/opt/piget/mjpeg-streamer/streamStart"
/do/nginx/authorize "/opt/piget/mjpeg-streamer/streamStop"

/system/restart nginx
