#!/bin/bash
. downloadModule nginx
. downloadModule camera
. downloadModule email
nginxInstall
nginxDir /opt/piget/pigetcam/www
#Add webserver
. downloadModule nginx
nginxInstall
nginxDir "/opt/piget/pigetcam"
#nginxAuthorize
#nginxHTTPS
