#!/bin/bash
#Add webserver
description "Install pigetcam"
downloadModule nginx
. /opt/piget/core/install/extendPath
nginxInstall
nginxDir "/opt/piget/pigetcam/www"
installer php5-curl

messagebox "Copy configurations"
makedir /opt/user/config/pigetcam
if [ -z /boot/piget/config/pigetcam ];then
  cp /opt/piget/pigetcam/default/* /opt/user/config/pigetcam
else
  cp /boot/piget/config/pigetcam/* /opt/user/config/pigetcam
fi

messagebox "Authorize reboot/halt"
nginxAuthorize /sbin/reboot
nginxAuthorize /sbin/halt

messagebox "Authorize pilight controls"
nginxAuthorize /opt/piget/pilightCommand/pilightCommandStart
nginxAuthorize /opt/piget/pilightCommand/pilightCommandStop

messagebox "Authorize email"
nginxAuthorize /opt/piget/pigetcam/pigetcamSendPicture

messagebox "Authorize Camera Stream"
nginxAuthorize /opt/piget/camera/cameraStreamStart
nginxAuthorize /opt/piget/camera/cameraStreamStop

messagebox "HTTPS activate"
#nginxHTTPS
