#!/bin/bash
/show/listecho "Send picture to default email" $OK
/do/mjpeg-streamer/savePicture "/tmp/tosend.jpg"

if [ $# -eq 1 ];then
	/do/email/send --Body "$1" --File "/tmp/tosend.jpg"
else
	/do/email/send --Body "Picture saved" --File "/tmp/tosend.jpg"
fi
rm "/tmp/tosend.jpg"
